# fib edit

[config]
output_dir      = "out/fib_edit"
composition     = "Z2ATitleBarV2"
timeline_offset = "00:00:00.000"

[config.defaults]
offset_x  = 0
offset_y  = 351
exit_style = "drop"


[[cards]]
id          = "electron_microscope_tour"
title       = "Mikhail"
extra_text  = "Zeptobars.com"
timecode    = "01:00:46.000"

[[cards]]
id          = "going_inside"
title       = "Going inside"
extra_text  = ""
timecode    = "01:02:21.467"

[[cards]]
id          = "chip_under_test"
title       = "Chip under test"
extra_text  = "Tiny Tapeout 8"
timecode    = "01:03:15.033"

[[cards]]
id          = "getting_better_images"
title       = "Getting better images"
extra_text  = "And why it takes longer"
timecode    = "01:04:25.167"

[[cards]]
id          = "design_under_test"
title       = "Design under test"
extra_text  = "Analog factory test"
timecode    = "01:05:09.600"

[[cards]]
id          = "ion_beam_ready"
title       = "Ion beam ready"
extra_text  = ""
timecode    = "01:06:03.067"

[[cards]]
id          = "finding_the_design"
title       = "Finding the design"
extra_text  = ""
timecode    = "01:06:52.433"


[[cards]]
id          = "zero_to_asic_cta"
composition = "Z2ACallToAction"
header       = "Join the Zero to ASIC Course"
line1  = "ZeroToASICcourse.com"
line2  = ""
timecode    = "01:08:09.067"


[[cards]]
id          = "setting_up_the_cut"
title       = "Setting up the cut"
extra_text  = ""
timecode    = "01:09:54.733"

[[cards]]
id          = "starting_the_cut"
title       = "Starting the cut"
extra_text  = ""
timecode    = "01:11:17.000"


[[cards]]
id          = "moment_of_failure"
title       = "Moment of failure"
extra_text  = ""
timecode    = "01:13:52.167"

[[cards]]
id          = "reconnection"
title       = "reconnection"
extra_text  = ""
timecode    = "01:14:41.400"

[[cards]]
id          = "ion_needle_in_place"
title       = "Ion needle in place"
extra_text  = ""
timecode    = "01:16:24.600"

[[cards]]
id          = "opening_the_flow"
title       = "Opening the flow"
extra_text  = ""
timecode    = "01:17:25.500"

[[cards]]
id          = "2_ways_to_deposit"
title       = "2 ways to deposit"
extra_text  = ""
timecode    = "01:18:13.467"

[[cards]]
id          = "voltage_is_rising"
title       = "Voltage is rising"
extra_text  = ""
timecode    = "01:18:47.300"

[[cards]]
id          = "wrapping_up"
title       = "Wrapping up"
extra_text  = ""
timecode    = "01:19:21.133"
