# fib edit

[config]
output_dir      = "out/fib_edit"
composition     = "Z2ATitleBarV2"
timeline_offset = "00:00:00.000"

[config.defaults]
offset_x  = 0
offset_y  = 351
exit_style = "drop"


[[cards]]
id          = "electron_microscope_tour"
title       = "Mikhail"
extra_text  = "Zeptobars.com"
timecode    = "01:00:46.000"


[[cards]]
id          = "getting_better_images"
title       = "Getting better images"
extra_text  = "And why it takes longer"
timecode    = "01:04:25.167"

[[cards]]
id          = "design_under_test"
title       = "Design under test"
extra_text  = "Analog factory test"
timecode    = "01:05:09.600"

[[cards]]
id          = "zero_to_asic_cta"
composition = "Z2ACallToAction"
header       = "Join the Zero to ASIC Course"
line1  = "ZeroToASICcourse.com"
line2  = ""
timecode    = "01:08:09.067"


[[cards]]
id          = "moment_of_failure"
title       = "Moment of failure"
extra_text  = ""
timecode    = "01:13:52.167"

[[cards]]
id          = "reconnection"
title       = "reconnection"
extra_text  = ""
timecode    = "01:14:41.400"

[[cards]]
id          = "gas_tube_in_place"
title       = "Gas tube in place"
extra_text  = ""
timecode    = "01:16:24.600"
