# fib edit

[config]
output_dir      = "out/fib_edit"
composition     = "Z2ATitleBarV2"
timeline_offset = "00:00:00.000"

[config.defaults]
offset_x  = 0
offset_y  = 351
exit_style = "drop"


[[cards]]
id          = "electron_microscope_tour"
title       = "Mikhail"
extra_text  = "Zeptobars.com"
timecode    = "01:00:43.06"

[[cards]]
id          = "tinytapeout8"
composition = "Z2ACallToAction"
header       = "Tiny Tapeout 8"
line1  = "tinytapeout.com/chips/tt08"
line2  = ""
timecode    = "01:03:14.11"

[[cards]]
id          = "getting_better_images"
title       = "Getting better images"
extra_text  = "And why it takes longer"
timecode    = "01:04:17.08"

[[cards]]
id          = "design_under_test"
title       = "Design under test"
extra_text  = "Analog factory test"
timecode    = "01:05:01.22"

[[cards]]
id          = "zero_to_asic_cta"
composition = "Z2ACallToAction"
header       = "Join the Zero to ASIC Course"
line1  = "ZeroToASICcourse.com"
line2  = ""
timecode    = "01:08:39.12"


[[cards]]
id          = "reconnection"
title       = "Reconnection"
extra_text  = ""
timecode    = "01:14:57.08"

[[cards]]
id          = "gas_tube_in_place"
title       = "Gas tube in place"
extra_text  = ""
timecode    = "01:16:39.23"
