// AUTO-GENERATED by scripts/gen-video-list.mjs — do not edit by hand
// Re-run via `make studio` or `make render-all` to pick up new videos.
export const BACKGROUND_VIDEOS = [
  "gf180_wafer.mov",
  "microchip-background-h264.mp4",
  "sine2.mp4",
  "tt_card_background.mp4"
] as const;
export type BackgroundVideo = (typeof BACKGROUND_VIDEOS)[number];
